### ISSUE TITLE
Add *.lot to .gitignore?

### ISSUE THREAD

**Issue by smiths** [icbicket/DataAnalysis#18]
I do not know the source, but there is a TestPlan.lot file that comes up when git status is run.  If it shouldn't be under version control, you should consider adding it to your .gitignore file.

**Comment by icbicket** [comment]
Looks like .lot and .lof are extra Latex files for the List of Tables and List of Figures. I've added both to the git ignore, 9f1c9f0. Thanks for alerting me!
