### ISSUE TITLE
Too well done 😬

### ISSUE THREAD

**Issue by keshavd** [icbicket/DataAnalysis#3]
Hi Isobel!

I read through your SRS! It was very well done. I found it easily digestible and I couldn't find any real flaws. Forgive the following issues if they sound nitpicky, I'm grasping at straws here lol

Cheers,
Keshav

**Comment by icbicket** [comment]
Thanks Keshav! That's always nice to hear! I will take a look at the things you suggested.
Cheers,
Isobel
