### ISSUE TITLE
Installation and running instructions?

### ISSUE THREAD

**Issue by smiths** [icbicket/DataAnalysis#32]
I suggest adding a file, either a README or an INSTALL file, that tells users how to get started with your software.  I believe that SpectrumImageAnalysisPy depends on libraries, like dm3_lib; you should let users know the dependencies and how they can resolve them.  

None of this is necessary for the CAS 741 course, since I know there is an issue with sharing data, but going forward, installability will be a significant part of whether your software is used by others or not.

**Comment by icbicket** [comment]
Oops, I have a DEPENDENCIES file, but left it on the master branch and forgot to add it to the course branch, my mistake. Thanks for pointing this out. I've updated and added this file to the branch Docs folder and  added something to the README to help users get started (commit 83a8e6b93b9ac9691ec103952736109874aaaa91).

**Comment by smiths** [comment]
That is helpful.  Thank you @icbicket.
